import type { Metadata } from "next";
import "./globals.css";
import AOSProvider from "@/components/global/aos-provider";
import Footer from "@/components/global/footer";

import { noto_sans } from "@/app/fonts/font";

export const metadata: Metadata = {
  title: "DNIL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto_sans.className} overflow-x-hidden bg-white`}>
        <AOSProvider>
          {children}
          <Footer />
        </AOSProvider>
      </body>
    </html>
  );
}
